### ISSUE TITLE
select query with alias auto order by id asc with no alias

### ISSUE THREAD

**Issue by trickymast3r** [ClanCats/Hydrahon#12]
select query with alias auto order by id asc with no alias

> select * from `hm2_user_balances` as `ub` inner join `hm2_users` as `u` on `u`.`id` = `ub`.`user_id` where `u`.`ref` = ? and `ub`.`type` = ? and `ub`.`amount` > ? order by RAND() asc, `id` asc limit 0, 1

**Comment by mario-deluna** [comment]
Could you explain a little bit more about the issue you are facing?
