### ISSUE TITLE
Remove single quotes from package name

### ISSUE THREAD

**Issue by AeonFr** [ClanCats/Hydrahon#19]
After trying to install the package with composer, of course I copied an pasted the command from the documentation, afterwards getting this weird message:

```
$ php composer.phar require 'clancats/hydrahon'


  [InvalidArgumentException]
  Could not find package 'clancats/hydrahon'.

  Did you mean this?
      clancats/hydrahon
```

I don't know if it's related with my version of composer (it should be pretty recent), but I will make a PR to solve this because I don't think there's any version where the name without single quotes would cause an issue.

**Comment by mario-deluna** [comment]
Thanks!
