### ISSUE TITLE
Native support for aggregate functions

### ISSUE THREAD

**Issue by lucas-facchini** [ClanCats/Hydrahon#2]
I have several statements that require the use of `COUNT` and `SUM` in my project. Since the library parses my input, I have to use the `raw(expression)` function which solves the problem, but it doesn't look good in the code.

Edit:
There's a function `count()` but it doesn't let you choose the column..

**Comment by mario-deluna** [comment]
Hello i've added a sql function system.

You have now following native helpers:

```php
// simple count
$table->select()->count();

// with special field
$table->select()->count('id');

// min value
$table->select()->min('views');

// max value
$table->select()->max('views');

// sum value
$table->select()->sum('views');

// avarage value
$table->select()->avg('views');
```

In more complex queries you can make use of the new field helpers:

```php
$query->addFieldCount('id');

// with alias
$query->addFieldCount('id', 'total_count');

// max 
$query->addFieldMax('views');

// min
$query->addFieldMin('views');

// sum
$query->addFieldSum('views');

// avarage
$query->addFieldAvg('views');

// rounding
$query->addFieldRound('price', 2, 'rounded_price');
```

See:
* d7d6b8d3394c121a581c69b30d3b48fc78fabac1
* b705ab7e36e6f0ed27cb08fbb1ca8c8fc0bb5155
* 76a580d6444a7faef4d0c4727f4ae2bacb22e9eb
* 094f70548f1c8ebd6f6f0e950a372f8540d036f0
