### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by dhutapratama** [ClanCats/Hydrahon#26]
Transaction is useful when updating money record. And i wish its added on the next release.

**Comment by mario-deluna** [comment]
If you are using PDO you can use it directly to start and commit transactions:

```php
$pdo->beginTransaction();
$h->table('data')->insert(['value' => 42])->execute();
$h->table('data')->insert(['value' => 84])->execute();
$pdo->commit();
```

Im not sure if it would be right to implement transactions into Hydrahon because it should stay only a query builder with no database abstraction layer.

**Comment by dhutapratama** [comment]
Okay, i stop this issue. Because the Hydrahon concept just for building query.
Thank you for the example code. I will try that
