### ISSUE TITLE
Incorrect type hinting

### ISSUE THREAD

**Issue by NickStallman** [ClanCats/Hydrahon#31]
I'm using PhpStan over my project and it has highlighted some incorrect type hinting.

Specifically SelectBase's where() functions specify the $column must be a string, however it could be an array or a callable as well which makes PhpStan unhappy.

**Comment by mario-deluna** [comment]
Hey there, this took a while but I finally tackled this issue. The latest release added a lot of type hints and fixed some wrong ones. Just let me know if you run in other ones.
