### ISSUE TITLE
Q: How do I increase the value on update?

### ISSUE THREAD

**Issue by Matix-Media** [ClanCats/Hydrahon#37]
Hi,

How can I increase an integer value on update?

LG Matix

**Comment by mario-deluna** [comment]
Hallo nochmals,

You can simply `+ 1` it:

```php
$h
    ->table('stats')
    ->update(['count' => new Expression('count + 1')])
    ->execute();
```

resulting in the following query:

```sql
update `stats` set `count` = count + 1
```

**Comment by Matix-Media** [comment]
Ah, tried it without expression.

Thanks for your help!👍
