### ISSUE TITLE
Relations in select

### ISSUE THREAD

**Issue by Matix-Media** [ClanCats/Hydrahon#38]
Does Hydrahon get the related tables (Foreign key) of a selected column?

**Comment by mario-deluna** [comment]
Hallo!

Im not sure I fully understand your question, hydrahon does not implement any fetching magic it is only a query string builder.  

Can you provide a code example to illustrate your question?

**Comment by Matix-Media** [comment]
What I mean, is there a function which does the join for a related table (using foreign keys) automatic? Technically I can just use join, but I have seen this function in other query builders too.

**Comment by mario-deluna** [comment]
At the moment there is no such thing in hydrahon, I also believe that relationship should be handled by an overlaying data base abstraction. But could you point me to a query builder that as you said implements this functionality? Im very curios and maybe im in the wrong here.

**Comment by Matix-Media** [comment]
Im not totally shure but I think the query builder for the python flask framework does that.
