### ISSUE TITLE
WhereOr access in function

### ISSUE THREAD

**Issue by eurairapelli** [ClanCats/Hydrahon#39]
Good night, 

How i can get variable from function where.
Example:

where(function($q) {
            $q->where('start','>=',$variable1)->orWhere('end','<=',$variable2);
        });

**Comment by mario-deluna** [comment]
Hello

Im not 100% sure I understand the question correctly. 

but if you mean to get the variables into the where scope you can just `use` them.

```php
->where(function($q) use($variable1, $variable2) {
    $q->where('start', '>=', $variable1)->orWhere('end','<=',$variable2);
});
```

**Comment by mario-deluna** [comment]
Im closing this Issue now. Let me know if the issue persists.

**Comment by eurairapelli** [comment]
Its works
