### ISSUE TITLE
 hello I would like a help with an INNER JOIN

### ISSUE THREAD

**Issue by zehenrique08** [ClanCats/Hydrahon#41]
I am not able to reproduce following sql using HYDRAHON

`SELECT
	a.idproduto AS id
	,b.nome AS nome
	,b.valor AS valor
	,a.qauntidade AS qauntidade
FROM 
	`quantos` a
INNER JOIN produtos b ON  a.idproduto = b.id
   where a.idcliente = 37`

**Comment by joaosn** [comment]
I have the same problem!!

**Comment by mario-deluna** [comment]
Hi there.

```php
$h
    ->table('quantos as a')
    ->select([
        'b.name as nome',
        'b.valor as valor',
        'b.qauntidade as qauntidade',
    ])
    ->innerJoin('produtos as b', 'a.idproduto', '=', 'b.id')
    ->where('a.idcliente', 37)
    ->execute();
```

produces the following query:


```sql
SELECT `a`.`idproduto` AS `id`,
       `b`.`name` AS `nome`,
       `b`.`valor` AS `valor`,
       `b`.`qauntidade` AS `qauntidade`
FROM `quantos` AS `a`
INNER JOIN `produtos` AS `b` ON `a`.`idproduto` = `b`.`id`
WHERE `a`.`idcliente` = ?
```

Is this what you are trying to achieve?

**Comment by joaosn** [comment]
Hi 
`$dados = Quanto::select([
            'idproduto as id',
            'b.name as nome',
            'b.valor as valor',
            'b.qauntidade as qauntidade',
        ])
        ->innerJoin('produtos as b', 'idproduto', '=', 'b.id')
        ->where('idcliente', $id)
        ->get();`

could you really give me an example using Static method?

**Comment by mario-deluna** [comment]
The class `Quanto` is not a part of hydrahon so without further information I cannot help you here. The only thing I see is that there is no table provided?

**Comment by joaosn** [comment]
hello friend obg for having answered, about 'How much' he and referring to the table created there in the database

for me to do simple select in the table I do like this
> `Quanto::select()->get();`

instead of so
> `$h->table(quanto)->select()->get();`

**Comment by joaosn** [comment]
already got a friend thanks for responding with your code got a better understanding of the inner join syntax
`
$dados = Quanto::select([
        'idproduto as id',
        'b.nome as nome',
        'b.valor as valor',
        'qauntidade as qauntidade',
        ])
        ->innerJoin('produtos as b', 'idproduto', '=', 'b.id')
        ->where('idcliente', $id)
        ->execute();
        file_put_contents('sql.txt',print_r($dados,true));
    
`

**Comment by mario-deluna** [comment]
Im closing this Issue now. Let me know if the issue persists.
