### ISSUE TITLE
how to do GROUP_CONCAT using Hydrahon

### ISSUE THREAD

**Issue by dht20** [ClanCats/Hydrahon#42]
im trying to do

`SELECT   id , GROUP_CONCAT(name) `
like this 
`select("id, GROUP_CONCAT(name) ")`

but i getting problemes , how can i do it properly?

**Comment by mario-deluna** [comment]
Hello there,

You can use the `Func` or `Expression` object.

```php 
use ClanCats\Hydrahon\Query\Sql\Func;

$h
    ->table('stats')
    ->select(['id', new Func('GROUP_CONCAT', 'name')])
    ->execute();
```

Result:

```sql
select `id`, GROUP_CONCAT(`name`) from `stats`
```
