### ISSUE TITLE
Bulk column problem

### ISSUE THREAD

**Issue by kingmaryjonatan** [ClanCats/Hydrahon#7]
Heya!

I find it frustrating while creating multiple bulk requests because:

🦀 🦀 

$q->where([array][0],'like', null, 'or');
$q->where([array][1], 'like', null, 'and');

`select 'cars.*' from 'cars'  where ('cars'.'title' = '%volvo%' or 'cars'.'slug' = '%volvo%') and ( 'cars'.'title' = '%AUX%' and 'cars'.'slug' = '%AUX%')`

This builds first bulk as 'or' and the other bulk as 'and' with an and between because the last bulk is and, switch the wheres and it's 'and' 'or' 'or'

😖 

My quickfix locally to get this to work is that all bulk columns have only the relation of 'or' in this case.

i would love to be able to use both or and and like :)

$q->where([array][0],'like', null, 'or');
and
$q->where([array][1], 'like', null, 'or');

`select 'cars.*' from 'cars'  where ('cars'.'title' like '%volvo%' or 'cars'.'slug' like '%volvo%') and ( 'cars'.'title' = '%AUX%' or 'cars'.'slug' = '%AUX%')`

https://github.com/ClanCats/Hydrahon/blob/master/src/Query/Sql/SelectBase.php#L126

My modified worthless version:

`$subquery->where($key, ($param1) ? $param1:null, ($param1) ? $val:null, 'or');`

**Comment by mario-deluna** [comment]
If I understand this right using callbacks should be the better solution:

```php
$h->table('cars')->select()
    ->where(function($q)   {
        $q->where('cars.title', 'like', '%volvo%');
        $q->orWhere('cars.slug', 'like', '%volvo%');
    })
    ->where(function($q)   {
        $q->where('cars.title', 'like', '%AUX%');
        $q->orWhere('cars.slug', 'like', '%AUX%');
    });
```

which will result in the following query string:

```sql
select * from `cars` where ( `cars`.`title` like ? or `cars`.`slug` like ? ) and ( `cars`.`title` like ? or `cars`.`slug` like ? )
```
and parameters: 
```json
["%volvo%","%volvo%","%AUX%","%AUX%"]
```

If im guessing right you are creating a search query with multiple keywords that need to match in at least one field. I would suggest building the query as following: 

```php
$searchString = "volvo aux";
$searchKeywords = explode(' ', $searchString);

$searchQuery = $h->table('cars')->select();

foreach($searchKeywords as $keyword)
{
	$searchQuery->where(function($q) use($keyword) {
		$q->where('cars.title', 'like', '%' . $keyword . '%');
	    $q->orWhere('cars.slug', 'like', '%' . $keyword . '%');
	});
}

var_dump($searchQuery->get());
```

This will give you the exact same query. 

Please let me know if this helps. 😊

**Comment by mario-deluna** [comment]
It has been a week, can I close this @kingmaryjonatan ?
